# Попробовал вручную отследить по логам куда делает запросы мессенджер Мах
# И пустить их трафик в DIRECT для избежания отслеживания IP-адресов
# VPN-сервисов и их дальнейших блокировок
# Также замечено использование мессенджером серверов Google
# Но они пока не будут добавлены в список

DOMAIN-SUFFIX,apptracer.ru
DOMAIN-SUFFIX,vk-analytics.ru
DOMAIN-SUFFIX,oneme.ru
DOMAIN-SUFFIX,okcdn.ru
DOMAIN-SUFFIX,gosuslugi.ru
DOMAIN-SUFFIX,max.ru
DOMAIN-SUFFIX,yandex.net
